### ISSUE TITLE
Netlink failure

### ISSUE THREAD

**Issue by tedsummers** [Ragnt/AngryOxide#13]
Hi,

From time to time I get this error in the output window. It does not appear to be a problem, but a hiccup that occurs and then continues to work as intended, however I thought I would share it with you anyway.

Error: "Netlink failure due to error: Wrapped IO error: No buffer space available (os error 105)

Screenshot: [https://i.ibb.co/SQZBgr1/Screenshot-from-2024-01-25-09-52-50.png](url)

I am using Alfa RTL8812AU Wifi adapters on my bare bones Kali Linux OS. Otherwise, it compiled with no issues, sees my GPS, and works as intended.

Thank You.

**Comment by Ragnt** [comment]
Thanks! 

This error is the result of netlink requests to update the interface data that happens when the channel changes. The actual source of the error is likely that the application isn’t reading the buffer fast enough for the kernel. In the latest versions this error is suppressed as it has no effect on operation, but I am making changes to the underlying nl80211-ng lib to solve it. 

Thank you for posting!
