### ISSUE TITLE
[Feature] Reinforcement Learning

### ISSUE THREAD

**Issue by aluminum-ice** [Ragnt/AngryOxide#23]
I am the developer of one popular [pwnagotchi.ai fork](https://github.com/aluminum-ice/pwnagotchi). I've been following AO and I am intrigued. I would like to proposal what I think would be a new feature for AO taken from [pwnagotchi](https://pwnagotchi.ai/): Use reinforcement learning to optimize probing and attacks. This would enable AO to more intelligently sweep through the parameter space (e.g., channels, lengths of time to listen) to maximize the chances of collecting handshakes. 

I'd love to help out time permitting. Happy to clarify my proposed enhancement/feature if its not clear.

**Comment by Ragnt** [comment]
I like the idea, but this would be quite a large amount of changes to the current codebase, I would consider this a version 2.0 feature. Note that we aren't even at 1.0 yet. I don't have the time currently due to real life (I'm not paid to maintain AO) to really get after these changes on my own.

But by all means, if you want to begin to map out how you would do this and start making necessary PR's, that would be cool. 

In the meantime, I suggest you join the discord to communicate any questions or changes you are making.

**Comment by Ragnt** [comment]
Sounds good.

There is also a plug-in framework in the works, and in theory lots of those params may be able to be modified at runtime by a plugin.

**Comment by pavlosSkev** [comment]
Reinforcement Learning is a gimmick for the most part in Pwnagotchi (unless I've missed experimental results comparing it to static configurations showing the RL outperformance). RL requires extremely large amount of data to perform well. Probably not worth the overhead for this feature.
